### ISSUE TITLE
大哥,这应该咋整,我在win7的tensorflow 上弄的

### ISSUE THREAD

**Issue by ithjz** [leido/char-rnn-cn#12]
![qq 20180528155351](https://user-images.githubusercontent.com/15103507/40604016-3d6a7812-6290-11e8-9a0b-9b6c6293f8f3.jpg)

**Comment by ithjz** [comment]
![qq 20180528160715](https://user-images.githubusercontent.com/15103507/40604315-3937b48e-6291-11e8-9ba2-b71e0efea7b0.jpg)

**Comment by ithjz** [comment]
E:\users\administrator\eclipse-workspace2\char-rnn-cn-master>python3 gen_lyrics.
py 0
'python3' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

E:\users\administrator\eclipse-workspace2\char-rnn-cn-master>python gen_lyrics.p
y 0
Traceback (most recent call last):
  File "gen_lyrics.py", line 7, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\__
init__.py", line 33, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\cu
dnn_rnn\__init__.py", line 34, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\cu
dnn_rnn\python\layers\__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\cu
dnn_rnn\python\layers\cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\cu
dnn_rnn\python\ops\cudnn_rnn_ops.py", line 21, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\rn
n\__init__.py", line 88, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\rn
n\python\ops\gru_ops.py", line 33, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\ut
il\loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\python\fra
mework\load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: D:\Users\Administrator\An
aconda3\lib\site-packages\tensorflow\contrib\rnn\python\ops\_gru_ops.dll not fou
nd

E:\users\administrator\eclipse-workspace2\char-rnn-cn-master>python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import  tensorflow
>>> ^Z


E:\users\administrator\eclipse-workspace2\char-rnn-cn-master>python gen_lyrics.p
y 0
Traceback (most recent call last):
  File "gen_lyrics.py", line 7, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\__
init__.py", line 33, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\cu
dnn_rnn\__init__.py", line 34, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\cu
dnn_rnn\python\layers\__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\cu
dnn_rnn\python\layers\cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\cu
dnn_rnn\python\ops\cudnn_rnn_ops.py", line 21, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\rn
n\__init__.py", line 88, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\rn
n\python\ops\gru_ops.py", line 33, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\contrib\ut
il\loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "D:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\python\fra
mework\load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: D:\Users\Administrator\An
aconda3\lib\site-packages\tensorflow\contrib\rnn\python\ops\_gru_ops.dll not fou
nd

E:\users\administrator\eclipse-workspace2\char-rnn-cn-master>
