### ISSUE TITLE
请问用的啥版本的TF？

### ISSUE THREAD

**Issue by wqw547243068** [leido/char-rnn-cn#5]
刚才运行了下，报错了：
```
--Training--
Vocabulary Size:  2636
Traceback (most recent call last):
  File "gen_lyrics.py", line 196, in <module>
    main(infer)
  File "gen_lyrics.py", line 184, in main
    run_fn(data, model, args)
  File "gen_lyrics.py", line 124, in train
    sess.run(tf.global_variables_initializer())
AttributeError: module 'tensorflow' has no attribute 'global_variables_initializer'
```

**Comment by jql1994** [comment]
运行最新0.12
